Repository AY2425S1-CS2103-F10-2/tp, pull requests merged in 2024-11, with the labels that each got.

#154 Allow edit command to delete optional fields
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.Medium

#167 Improved view command
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/secondViewTwoResult.png
  docs/images/viewOneResult.png
  docs/images/viewTwoResult.png
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonCardFull.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/PersonListCardFull.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Labels: type.Enhancement, priority.Medium, severity.Medium, alpha-bug

#174 Update duplicate definition of persons to be case insensitive
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Bug, alpha-bug

#172 Update phone parsing
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/EmergencyContactTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: type.Enhancement, priority.Medium, severity.Medium, alpha-bug

#173 Update edit command to include remark
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Remark.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: alpha-bug

#170 Enable text wrapping for names
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListCardFull.fxml
Labels: type.Chore, alpha-bug

#171 Modify dateOfLastVisit to use LocalDate instead of String
  src/main/java/seedu/address/model/person/DateOfLastVisit.java
  src/main/java/seedu/address/model/person/PersonComparator.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/model/person/DateOfLastVisitTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Chore, priority.Medium, severity.Medium, alpha-bug

#183 Update UG with field requirements
  docs/UserGuide.md
Labels: type.Chore, priority.Medium, alpha-bug

#188 Fix wrong version attribute
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High, alpha-bug

#200 Update user profile and story
  docs/DeveloperGuide.md
Labels: alpha-bug

#204 Rename log file to socialbook.log
  src/main/java/seedu/address/commons/core/LogsCenter.java
Labels: alpha-bug

#190 Update find to find tags
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
Labels: priority.High

#206 docs: Remove tutorial section
  docs/SettingUp.md
  docs/_markbind/layouts/default.md
Labels: alpha-bug

#210 Make prefix detection case insensitive
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
Labels: priority.Medium, alpha-bug

#211 Improve clarity for SortCommand format
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: alpha-bug

#212 Update Viewing to match person for sorting
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Labels: alpha-bug

#218 Improve error message and UG clarity
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/DateOfLastVisit.java
Labels: priority.High, alpha-bug
